//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        public int Id { get; set; }
        public Nullable<int> pay_office_number { get; set; }
        public Nullable<System.DateTime> C_date_of_operation { get; set; }
        public Nullable<int> check_number { get; set; }
        public Nullable<double> money_amount { get; set; }
        public string Name_of_cashier { get; set; }
    }
}
